package com.example.aidetest

/** Central catalog of MyTools pages. Edit display name/category/icon here without searching MainActivity. */
data class ToolInfo(val id: String, val name: String, val category: String, val icon: String = "tools")

object ToolRegistry {
    val categories = listOf("File", "Developer", "Network", "System", "Calculator", "Utility", "Security", "Image", "IoT", "Web", "Finance", "Workspace", "App")

    val tools = listOf(
        ToolInfo("filemanager", "File Manager", "File"),
        ToolInfo("recentfiles", "Recent Files", "File"),
        ToolInfo("backuprestore", "Backup & Restore", "File"),
        ToolInfo("zip", "ZIP Tool", "File"),
        ToolInfo("fileconvert", "File Converter", "File"),
        ToolInfo("filehashcompare", "File Hash Compare", "File"),
        ToolInfo("fileencryption", "File Encryption", "File"),
        ToolInfo("filesearch", "File Search", "File"),
        ToolInfo("duplicatefinder", "Duplicate Finder", "File"),
        ToolInfo("largefilefinder", "Large File Finder", "File"),
        ToolInfo("editor", "Code Editor", "Developer"),
        ToolInfo("githubzip", "GitHub ZIP", "Developer"),
        ToolInfo("restclient", "REST Client", "Developer"),
        ToolInfo("websocket", "WebSocket", "Developer"),
        ToolInfo("webproject", "Web Project Builder", "Developer"),
        ToolInfo("markdown", "Markdown Viewer", "Developer"),
        ToolInfo("sql", "SQL Tools", "Developer"),
        ToolInfo("yaml", "YAML Formatter", "Developer"),
        ToolInfo("toml", "TOML Inspector", "Developer"),
        ToolInfo("cron", "Cron Helper", "Developer"),
        ToolInfo("wifi", "Wi-Fi Info", "Network"),
        ToolInfo("dns", "DNS Lookup", "Network"),
        ToolInfo("rdns", "Reverse DNS", "Network"),
        ToolInfo("port", "Port Checker", "Network"),
        ToolInfo("publicip", "Public IP", "Network"),
        ToolInfo("ping", "Ping", "Network"),
        ToolInfo("ipinfo", "IP Info", "Network"),
        ToolInfo("ssl", "SSL Checker", "Network"),
        ToolInfo("network", "Network Info", "Network"),
        ToolInfo("netscanner", "Network Scanner", "Network"),
        ToolInfo("whois", "WHOIS", "Network"),
        ToolInfo("traceroute", "Traceroute", "Network"),
        ToolInfo("subnetcalc", "Subnet Calculator", "Network"),
        ToolInfo("networkcenter", "Network Center", "Network"),
        ToolInfo("system", "System Info", "System"),
        ToolInfo("deviceinfo", "Device Info", "System"),
        ToolInfo("storage", "Storage Analyzer", "System"),
        ToolInfo("apps", "App Manager", "System"),
        ToolInfo("battery", "Battery Info", "System"),
        ToolInfo("clipboard", "Clipboard Manager", "System"),
        ToolInfo("systemcenter", "System Center", "System"),
        ToolInfo("number", "Calculator Hub", "Calculator"),
        ToolInfo("basiccalc", "Basic Calculator", "Calculator"),
        ToolInfo("scicalc", "Scientific Calculator", "Calculator"),
        ToolInfo("percentcalc", "Percentage", "Calculator"),
        ToolInfo("fractioncalc", "Fraction", "Calculator"),
        ToolInfo("ratiocalc", "Ratio", "Calculator"),
        ToolInfo("unitcalc", "Unit Converter", "Calculator"),
        ToolInfo("areacalc", "Area", "Calculator"),
        ToolInfo("volumecalc", "Volume", "Calculator"),
        ToolInfo("speedcalc", "Speed", "Calculator"),
        ToolInfo("timecalc", "Time", "Calculator"),
        ToolInfo("datecalc", "Date", "Calculator"),
        ToolInfo("loancalc", "Loan", "Calculator"),
        ToolInfo("fuelcalc", "Fuel", "Calculator"),
        ToolInfo("pivotcalc", "Pivot Point", "Calculator"),
        ToolInfo("dividercalc", "Voltage Divider", "Calculator"),
        ToolInfo("dcacalc", "DCA", "Calculator"),
        ToolInfo("pwmcalc", "PWM", "Calculator"),
        ToolInfo("spritecalc", "Sprite Sheet", "Calculator"),
        ToolInfo("installcalc", "Installment", "Calculator"),
        ToolInfo("powercalc", "Power", "Calculator"),
        ToolInfo("aspectcalc", "Aspect Ratio", "Calculator"),
        ToolInfo("pphcalc", "PPN / PPh", "Calculator"),
        ToolInfo("riskcalc", "Risk / Reward", "Calculator"),
        ToolInfo("compoundcalc", "Compound Interest", "Calculator"),
        ToolInfo("margincalc", "Margin / Tax", "Calculator"),
        ToolInfo("discountcalc", "Tiered Discount", "Calculator"),
        ToolInfo("datacalc", "Data Unit", "Calculator"),
        ToolInfo("pressurecalc", "Pressure", "Calculator"),
        ToolInfo("worktimecalc", "Work Time", "Calculator"),
        ToolInfo("basecalc", "Base Converter", "Calculator"),
        ToolInfo("equationcalc", "Equation", "Calculator"),
        ToolInfo("hash", "Hash Generator", "Utility"),
        ToolInfo("base64", "Base64", "Utility"),
        ToolInfo("url", "URL Tools", "Utility"),
        ToolInfo("regex", "Regex Tester", "Utility"),
        ToolInfo("uuid", "UUID Generator", "Utility"),
        ToolInfo("random", "Random", "Utility"),
        ToolInfo("checksum", "Checksum", "Utility"),
        ToolInfo("hex", "Hex", "Utility"),
        ToolInfo("base32", "Base32", "Utility"),
        ToolInfo("timestamp", "Timestamp", "Utility"),
        ToolInfo("unicode", "Unicode", "Utility"),
        ToolInfo("urlparser", "URL Parser", "Utility"),
        ToolInfo("mime", "MIME", "Utility"),
        ToolInfo("uuidbatch", "UUID Batch", "Utility"),
        ToolInfo("base64file", "Base64 File", "Utility"),
        ToolInfo("httpheaders", "HTTP Headers", "Utility"),
        ToolInfo("textreplace", "Text Replace", "Utility"),
        ToolInfo("wordfreq", "Word Frequency", "Utility"),
        ToolInfo("textstat", "Text Statistics", "Utility"),
        ToolInfo("case", "Case Converter", "Utility"),
        ToolInfo("dedupe", "Deduplicate", "Utility"),
        ToolInfo("compare", "Text Compare", "Utility"),
        ToolInfo("slug", "Slug Generator", "Utility"),
        ToolInfo("lorem", "Lorem Ipsum", "Utility"),
        ToolInfo("password", "Password Generator", "Utility"),
        ToolInfo("token", "Token Generator", "Utility"),
        ToolInfo("jwt", "JWT", "Utility"),
        ToolInfo("hmac", "HMAC", "Utility"),
        ToolInfo("totp", "TOTP", "Utility"),
        ToolInfo("aes", "AES", "Utility"),
        ToolInfo("securitycenter", "Security Center", "Security"),
        ToolInfo("passwordstrength", "Password Strength", "Security"),
        ToolInfo("passwordanalyzer", "Password Strength Analyzer", "Security"),
        ToolInfo("breachchecker", "Data Breach Checker", "Security"),
        ToolInfo("securenotes", "Secure Notes", "Security"),
        ToolInfo("totpvault", "2FA Manager", "Security"),
        ToolInfo("pgp", "PGP", "Security"),
        ToolInfo("sshkeygen", "SSH Key Generator", "Security"),
        ToolInfo("certviewer", "Certificate Viewer", "Security"),
        ToolInfo("virusscanner", "Virus Scanner", "Security"),
        ToolInfo("urlsafety", "URL Safety", "Security"),
        ToolInfo("steganography", "Steganography", "Security"),
        ToolInfo("color", "Color Tools", "Image"),
        ToolInfo("uicolorcalc", "UI Color Picker", "Image"),
        ToolInfo("imageinfo", "Image Metadata", "Image"),
        ToolInfo("imagetools", "Image Tools", "Image"),
        ToolInfo("ocr", "OCR", "Image"),
        ToolInfo("qr", "QR Tools", "Image"),
        ToolInfo("esp", "ESP Tools", "IoT"),
        ToolInfo("espdiscover", "ESP Discovery", "IoT"),
        ToolInfo("ledstudio", "ESP LED Studio", "IoT"),
        ToolInfo("espdevice", "ESP Device Manager", "IoT"),
        ToolInfo("espgpio", "ESP GPIO", "IoT"),
        ToolInfo("espsensor", "ESP Sensors", "IoT"),
        ToolInfo("espwifi", "ESP Wi-Fi", "IoT"),
        ToolInfo("espota", "ESP OTA", "IoT"),
        ToolInfo("esphttp", "ESP HTTP", "IoT"),
        ToolInfo("espmqtt", "ESP MQTT", "IoT"),
        ToolInfo("espusb", "ESP USB", "IoT"),
        ToolInfo("espserial", "ESP Serial", "IoT"),
        ToolInfo("iotdashboard", "IoT Dashboard", "IoT"),
        ToolInfo("espstudio", "ESP Studio", "IoT"),
        ToolInfo("visualwiring", "Visual Wiring", "IoT"),
        ToolInfo("http", "HTTP Server", "Web"),
        ToolInfo("webhostwifi", "HTML Hosting Wi-Fi", "Web"),
        ToolInfo("financereader", "Finance Reader", "Finance"),
        ToolInfo("financedashboard", "Finance Dashboard", "Finance"),
        ToolInfo("financestudio", "Finance Studio", "Finance"),
        ToolInfo("workspace", "Workspace Center", "Workspace"),
        ToolInfo("plugincenter", "Plugin Center", "Workspace"),
        ToolInfo("customtools", "Tool Customization", "Workspace"),
        ToolInfo("studiocenter", "Studio Center", "Workspace"),
        ToolInfo("networkstudio", "Network Studio", "Workspace"),
        ToolInfo("developerstudio", "Developer Studio", "Workspace"),
        ToolInfo("filestudio", "File Studio", "Workspace"),
        ToolInfo("systemstudio", "System Studio", "Workspace"),
        ToolInfo("utilitystudio", "Utility Studio", "Workspace"),
        ToolInfo("apk", "APK Inspector", "App"),
        ToolInfo("apkanalyzer", "APK Analyzer", "App"),
        ToolInfo("apkcompare", "APK Compare", "App"),
        ToolInfo("unitconverter", "Unit Converter Pro", "App"),
        ToolInfo("helpbot", "HelpBot Offline", "App"),
    )

    fun byId(id: String): ToolInfo? = tools.firstOrNull { it.id == id }
}
